keys:
  - &admin_lorenzo age1fhrjrmd82u5ncg4s6qxkt883756aafl5x6w25k555sq4sk5tw35qy8upge
  - &server_znet-de-nue1 age14aa7uhr0m4k663h0rh965d2ng8yte67l28hmvyr2aeu9r8sqnafsrxrs5k
  - &server_znet-de-dus1 age1h8m7srhyqquhxvkavklwm905wkv9lcr27mwqzexpa6wahehsk4hsmfeydp
  - &server_znet-it-mil1 age16svaesf9w9yu773gema2f8x7cy74ukn0pe7z05vgp86qdhx8yuzqfwmt03
  - &server_znet-it-mil2 age1efwuw5tuavrsm74nese6d9fdammlfj0cfygxuaadlnq46658gc8qtmrt4d
  - &server_znet-it-mil3 age1ntffp5j2s0vfr84hc3md3sxce2skvaqpj6ryqshp75870l4wza6qv5zmac
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_lorenzo
      - *server_znet-de-nue1
      - *server_znet-de-dus1
      - *server_znet-it-mil1
      - *server_znet-it-mil2
      - *server_znet-it-mil3
