[hosts.znet-fr-par1]
ifname_ext = "eth0"
network = "znet"
ipv4 = { addr = "185.10.17.55/32", gateway = "185.10.17.254" }
ipv6 = { addr = "2a07:8dc0:19:12f::1/128", gateway = "fe80::1"}
dns = [ "185.10.16.252", "185.154.155.252", "185.10.17.251", "2a07:8dc0:19::251", "2a07:8dc1:20::252" ]
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJ9Bkr4aWdLCk7jifA2jkem0pNlgnCuUpW2Q6o/M7Gd7"
wg_pubkey = "6nomFb2YigoDJgDcshAYZ9sClKjgooPjE7nmXOv6lzw="
wg_linklocal = "fe80::2:1/64"
wg_remoteport = 14142
znet_loopback = "2a0e:8f02:2142:f::1/128"

[hosts.znet-de-nue1]
aarch = "x86_64-linux"
hardware = "prager-vps"
ifname_ext = "ens18"
network = "znet"
ipv4 = { addr = "212.46.59.59/32", gateway = "212.46.59.1" }
dns = [ "212.46.59.1", "1.1.1.1" ]
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIA7QTrUKg6UXmFdRCjLukezv6D97kzVNpFHwTjwomBmd"
wg_pubkey = "mG7OIIdsQ3T4JIJVjk/s28Vqw+GaP9QiXN60LRpiQiU="
wg_linklocal = "fe80::4:1/64"
wg_remoteport = 14144
znet_loopback = "2a0e:8f02:2144:f::1/128"

[hosts.znet-de-dus1]
aarch = "x86_64-linux"
hardware = "contabo-vps"
ifname_ext = "ens18"
network = "znet"
ipv4 = { addr = "194.163.158.84/32", gateway = "194.163.128.1" }
ipv6 = { addr = "2a02:c206:2178:8776::1/128", gateway = "fe80::1" }
dns = [ "161.97.189.52", "161.97.189.51", "2a02:c206:5028::2:53", "2s02:c206:5028::1:53" ]
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMx1T3+kw11sOFDmqWOf1jiDnIv5NGQGbJtH/jsoiCHB"
wg_pubkey = "Q/R/nCvikTz5yFzuOfZXYvWjhBaHaOufGW+R8V2Ny0U="
wg_linklocal = "fe80::5:1/64"
wg_remoteport = 14145
znet_loopback = "2a0e:8f02:2145:f::1/128"

[hosts.znet-it-mil1]
aarch = "aarch64-linux"
hardware = "oracle-vps-arm"
ifname_ext = "enp0s6"
network = "znet"
ipv4 = { addr = "10.0.0.112/32", gateway = "10.0.0.1", ext = "89.168.26.250" }
dns = [ "169.254.169.254" ]
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIuMZ6n+4np+AV6EC8HaJCKo1ru/3F2T1ushw9CVyexp"
wg_pubkey = "uHC6DxWxPIG7J6865SKhOObl6fJcFU1Slfd2YUT+fF4="
wg_linklocal = "fe80::6:1/64"
wg_remoteport = 14146
znet_loopback = "2a0e:8f02:2146:f::1/128"

[hosts.znet-it-mil2]
aarch = "aarch64-linux"
hardware = "oracle-vps-arm"
ifname_ext = "enp0s6"
network = "znet"
ipv4 = { addr = "10.0.0.247/32", gateway = "10.0.0.1", ext = "129.152.1.131" }
dns = [ "169.254.169.254" ]
ssh_pubkey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIk64uHd8gova+QyII2bZs0L/59S8bt3f+hy2oIEkWXd"
wg_pubkey = "cfR0gLUDyXg4acY5C+Kec4BpAfHQaKIzGHInTD+f0VA="
wg_linklocal = "fe80::7:1/64"
wg_remoteport = 14147
znet_loopback = "2a0e:8f02:2146:f::2/128"

[hosts.lilik-it-flr1a]
ifname_ext = "eth0"
network = "lilik"
ipv4 = { addr = "10.150.46.140/24", gateway = "10.150.46.1", ext = "150.217.18.45" }
ipv6 = { addr = "2001:760:2c05:18:c9ea:de73:a2fc:140/112" }
dns = [ "150.217.1.32", "8.8.8.8", "1.1.1.1" ]
wg_pubkey = "kSFbEkjlSFOnVEKUt2ufcR+KDzWFRc98neg30if/gBc="
wg_linklocal = "fe80::0:1/64"
wg_remoteport = 14150
wg_altlocalport = 1
znet_loopback = "2a0e:8f02:2140:f::2/128"

[hosts.lilik-it-flr1b]
ifname_ext = "eth0"
network = "lilik"
ipv4 = { addr = "10.150.42.77/24", gateway = "10.150.42.1", ext = "150.217.18.45" }
ipv6 = { addr = "2001:760:2c05:18:c9ea:de73:a2fb:9451/112" }
dns = [ "10.150.42.1", "8.8.8.8", "2620:fe::9" ]
wg_pubkey = "ukAjkPVuaVKbzVm+zTUAI6zqY4+dbsVvLONOqHRRJQU="
wg_linklocal = "fe80::0:2/64"
wg_remoteport = 14140
znet_loopback = "2a0e:8f02:2140:f::1/128"
